### ISSUE TITLE
Problem with the arduino uugear id

### ISSUE THREAD

**Issue by afakharany93** [shawnu/UUGear#14]
Dear UUGear
My issue is that when I send U01 on the serial monitor with the arduino it returns 	1i:) 
and when I connect the arduino with the raspberry pi and run ./lsuu it says 0 device(s) found.
please help, and thnx

**Comment by shawnu** [comment]
Seems the uugear id was not written into EEPROM. This could happen if your EEPROM has any content. You can modify the UUGear.ino file to call generateID() function explicitly (for only once).

The same issue has discussed in https://github.com/shawnu/UUGear/issues/5

**Comment by afakharany93** [comment]
Thnx for replying, it worked (y)
