### ISSUE TITLE
can we increase MAX_MSG_PARTS ?

### ISSUE THREAD

**Issue by afakharany93** [shawnu/UUGear#18]
Hi Shawn,
Thanks for your library, its really good work (y)
I'm using your library in my graduation project and I'm tinkering with it, is it possible to increase the message parts sent from the Rpi to the arduino to exceed 8 parts ?

**Comment by shawnu** [comment]
Yes, it is possible.

Currently there is no message that contains more than 5 parts. Of course you can define your own message a let it contains more than 8 parts. The MAX_MSG_PARTS is just there for allocating enough memory for parsing the message parts.

**Comment by afakharany93** [comment]
thanks (y)
