### ISSUE TITLE
Problem when I scan the voltage！

### ISSUE THREAD

**Issue by JamesLiAndroid** [shawnu/UUGear#19]
I have read your article http://www.uugear.com/portfolio/raspberry-pi-measures-voltage-via-arduino/ 

My problem is
---when read voltage value, it must be added sleep(0.2).Could it be read without sleep?
---the value could be transfered as String?I try it but it may not be really usage.
---when I start to read voltage, should I initialize the arduino port?
---when I use the Paho to send a message to my server,the Paho is not working,is it have attachment?

thanks!

**Comment by shawnu** [comment]
Yes it could be read without any sleep.

The value is an integer, you can google a way to convert it to string.

You need to initialize the UUGear device before reading it, as shown in the example.

I am not familiar with Paho, and have no idea how you used it. I think it has nothing to do with this library.

**Comment by JamesLiAndroid** [comment]
OK,I think I have got the way to solve my problem.Thanks!
